// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: ingestion.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Public ingestion input.
// Thin wrapper over canonical EventPayload.
type IngestionEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *EventPayload          `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	Meta          map[string]string      `protobuf:"bytes,2,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // optional metadata (e.g. request_id from gateway)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestionEvent) Reset() {
	*x = IngestionEvent{}
	mi := &file_ingestion_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestionEvent) ProtoMessage() {}

func (x *IngestionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestionEvent.ProtoReflect.Descriptor instead.
func (*IngestionEvent) Descriptor() ([]byte, []int) {
	return file_ingestion_proto_rawDescGZIP(), []int{0}
}

func (x *IngestionEvent) GetEvent() *EventPayload {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *IngestionEvent) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

type IngestionAsyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // event id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestionAsyncResponse) Reset() {
	*x = IngestionAsyncResponse{}
	mi := &file_ingestion_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestionAsyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestionAsyncResponse) ProtoMessage() {}

func (x *IngestionAsyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestionAsyncResponse.ProtoReflect.Descriptor instead.
func (*IngestionAsyncResponse) Descriptor() ([]byte, []int) {
	return file_ingestion_proto_rawDescGZIP(), []int{1}
}

func (x *IngestionAsyncResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type IngestionSyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`             // event id
	Verdict       string                 `protobuf:"bytes,2,opt,name=verdict,proto3" json:"verdict,omitempty"`   // approved | flagged | rejected
	Response      []byte                 `protobuf:"bytes,3,opt,name=response,proto3" json:"response,omitempty"` // sync-only payload (MessagePack-encoded map with dynamic fields: behavior, reason, redaction.findings, etc.)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestionSyncResponse) Reset() {
	*x = IngestionSyncResponse{}
	mi := &file_ingestion_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestionSyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestionSyncResponse) ProtoMessage() {}

func (x *IngestionSyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestionSyncResponse.ProtoReflect.Descriptor instead.
func (*IngestionSyncResponse) Descriptor() ([]byte, []int) {
	return file_ingestion_proto_rawDescGZIP(), []int{2}
}

func (x *IngestionSyncResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *IngestionSyncResponse) GetVerdict() string {
	if x != nil {
		return x.Verdict
	}
	return ""
}

func (x *IngestionSyncResponse) GetResponse() []byte {
	if x != nil {
		return x.Response
	}
	return nil
}

var File_ingestion_proto protoreflect.FileDescriptor

const file_ingestion_proto_rawDesc = "" +
	"\n" +
	"\x0fingestion.proto\x12\tingestion\x1a\fcommon.proto\"\xae\x01\n" +
	"\x0eIngestionEvent\x12*\n" +
	"\x05event\x18\x01 \x01(\v2\x14.common.EventPayloadR\x05event\x127\n" +
	"\x04meta\x18\x02 \x03(\v2#.ingestion.IngestionEvent.MetaEntryR\x04meta\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"(\n" +
	"\x16IngestionAsyncResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"]\n" +
	"\x15IngestionSyncResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\averdict\x18\x02 \x01(\tR\averdict\x12\x1a\n" +
	"\bresponse\x18\x03 \x01(\fR\bresponse2\xaa\x01\n" +
	"\x10IngestionService\x12K\n" +
	"\vIngestAsync\x12\x19.ingestion.IngestionEvent\x1a!.ingestion.IngestionAsyncResponse\x12I\n" +
	"\n" +
	"IngestSync\x12\x19.ingestion.IngestionEvent\x1a .ingestion.IngestionSyncResponseB Z\x1eswiftward/internal/proto;protob\x06proto3"

var (
	file_ingestion_proto_rawDescOnce sync.Once
	file_ingestion_proto_rawDescData []byte
)

func file_ingestion_proto_rawDescGZIP() []byte {
	file_ingestion_proto_rawDescOnce.Do(func() {
		file_ingestion_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ingestion_proto_rawDesc), len(file_ingestion_proto_rawDesc)))
	})
	return file_ingestion_proto_rawDescData
}

var file_ingestion_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_ingestion_proto_goTypes = []any{
	(*IngestionEvent)(nil),         // 0: ingestion.IngestionEvent
	(*IngestionAsyncResponse)(nil), // 1: ingestion.IngestionAsyncResponse
	(*IngestionSyncResponse)(nil),  // 2: ingestion.IngestionSyncResponse
	nil,                            // 3: ingestion.IngestionEvent.MetaEntry
	(*EventPayload)(nil),           // 4: common.EventPayload
}
var file_ingestion_proto_depIdxs = []int32{
	4, // 0: ingestion.IngestionEvent.event:type_name -> common.EventPayload
	3, // 1: ingestion.IngestionEvent.meta:type_name -> ingestion.IngestionEvent.MetaEntry
	0, // 2: ingestion.IngestionService.IngestAsync:input_type -> ingestion.IngestionEvent
	0, // 3: ingestion.IngestionService.IngestSync:input_type -> ingestion.IngestionEvent
	1, // 4: ingestion.IngestionService.IngestAsync:output_type -> ingestion.IngestionAsyncResponse
	2, // 5: ingestion.IngestionService.IngestSync:output_type -> ingestion.IngestionSyncResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ingestion_proto_init() }
func file_ingestion_proto_init() {
	if File_ingestion_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ingestion_proto_rawDesc), len(file_ingestion_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ingestion_proto_goTypes,
		DependencyIndexes: file_ingestion_proto_depIdxs,
		MessageInfos:      file_ingestion_proto_msgTypes,
	}.Build()
	File_ingestion_proto = out.File
	file_ingestion_proto_goTypes = nil
	file_ingestion_proto_depIdxs = nil
}
