ALTER TABLE trades DROP COLUMN IF EXISTS fee;
ALTER TABLE trades DROP COLUMN IF EXISTS fee_asset;
ALTER TABLE trades DROP COLUMN IF EXISTS fee_value;
ALTER TABLE agent_state DROP COLUMN IF EXISTS total_fees;
